name: group_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  analyzer: ^4.6.0
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  file_picker: any
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  flashy_tab_bar2: ^0.0.5
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.6
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.2
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: any
  json_annotation: ^4.7.0
  location: ^4.4.0
  open_filex: any
  path_provider: any
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  unicons: ^2.1.0
  uuid: any

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 100
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 300
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf
  assets:
    - assets/images/

